# Generated by Django 3.0.1 on 2020-01-16 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_text', models.CharField(max_length=200)),
                ('start_check_in_date', models.DateTimeField(verbose_name='Check in date')),
                ('end_check_out_date', models.DateTimeField(verbose_name='Check out date')),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateTimeField(verbose_name='Check in date')),
                ('check_out_date', models.DateTimeField(verbose_name='Check out date')),
                ('pax', models.IntegerField(default=0)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=20)),
                ('booking_date', models.DateTimeField(verbose_name='Booking date')),
                ('booking_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('booking_comments', models.CharField(max_length=200)),
                ('booking_localizator', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonRoomPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('booking_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.BookingSeason')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.RoomType')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonBookingCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Check in date')),
                ('check_in', models.BooleanField()),
                ('check_out', models.BooleanField()),
                ('room_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.RoomBooking')),
            ],
        ),
        migrations.CreateModel(
            name='RoomDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number_text', models.CharField(max_length=3)),
                ('room_max_pax', models.IntegerField(default=0)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.RoomType')),
            ],
        ),
        migrations.AddField(
            model_name='roombooking',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.RoomType'),
        ),
    ]
