# Generated by Django 3.0.1 on 2020-01-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='booking_localizator',
            field=models.CharField(max_length=6),
        ),
    ]
