# Generated by Django 3.0.1 on 2020-01-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_auto_20200116_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdescription',
            name='room_max_pax',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room_type_max_pax',
            field=models.IntegerField(default=0),
        ),
    ]
