# Generated by Django 3.0.1 on 2020-01-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_auto_20200116_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='booking_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
    ]
