# Generated by Django 3.0.1 on 2020-01-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_auto_20200119_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='check_in_date',
            field=models.DateField(verbose_name='Check in date'),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='check_out_date',
            field=models.DateField(verbose_name='Check out date'),
        ),
    ]
