# Generated by Django 3.0.1 on 2020-01-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_auto_20200121_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingseason',
            name='end_check_out_date',
            field=models.DateTimeField(verbose_name='Season ends'),
        ),
        migrations.AlterField(
            model_name='bookingseason',
            name='season_text',
            field=models.CharField(max_length=200, verbose_name='Season title'),
        ),
        migrations.AlterField(
            model_name='bookingseason',
            name='start_check_in_date',
            field=models.DateTimeField(verbose_name='Season start'),
        ),
        migrations.AlterField(
            model_name='seasonbookingcalendar',
            name='check_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seasonbookingcalendar',
            name='check_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seasonbookingcalendar',
            name='date',
            field=models.DateField(),
        ),
    ]
