# Generated by Django 3.0.1 on 2020-01-24 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_auto_20200123_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.RoomDescription'),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='pax',
            field=models.IntegerField(default=1),
        ),
    ]
