# Generated by Django 3.0.1 on 2020-01-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_auto_20200124_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonbookingcalendar',
            name='status',
            field=models.CharField(blank=True, choices=[('b', 'Bloqueada'), ('r', 'Reserva'), ('d', 'Disponible')], default='d', help_text='Disponibilidad', max_length=1),
        ),
    ]
