# Generated by Django 3.0.1 on 2020-01-27 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_seasonbookingcalendar_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='booking_comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='pax',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.RoomDescription'),
        ),
    ]
